#!/usr/bin/env bun
// revu-app's commands, run with the exact2 checkout named by EXACT2
// (default ../../exact2). Generated by `exact new`; `bun exact.mjs update` rewrites
// this file, the crates.io patches, the toolchain and the exact2 dependency paths. The app's own
// verbs live in app.json's `commands`, which update leaves alone.
import { spawn, spawnSync } from 'node:child_process';
import { appendFileSync, existsSync, mkdirSync, readFileSync } from 'node:fs';
import { constants } from 'node:os';
import { relative, resolve } from 'node:path';

const EXACT2 = resolve(import.meta.dir, process.env.EXACT2 ?? "../../exact2");
const [verb, ...rest] = process.argv.slice(2);
const host = (verb === 'test' || verb === 'agent') && rest[0] && !rest[0].startsWith('-') ? rest.shift() : 'web';
const verbs = {
  web: ['host/web/dev.mjs', '--app', 'revu-app'],
  'web-build': ['host/web/build.mjs', 'revu-app'],
  test: ['scripts/agent.mjs', host, '--app', 'revu-app'],
  agent: ['scripts/agent.mjs', host, '--app', 'revu-app'],
  ios: ['host/apple/build.mjs', '--ios', 'revu-app-apple'],
  mac: ['host/apple/build.mjs', 'revu-app-apple'],
  update: ['scripts/exact.mjs', 'new', import.meta.dir, '--update'],
  contract: ['scripts/exact.mjs', 'contract'],
  hatch: ['scripts/exact.mjs', 'hatch'],
  feedback: ['scripts/feedback.mjs'],
};
// The app's own verbs (paint, minesweeper, ledger: a regenerated file dropped the ones added here): app.json's
// `commands`, each a command as argv (`"verify": ["bun", "verify.mjs"]`), run in this directory with the
// arguments after the verb. A game's app.json is optional.
const manifest = resolve(import.meta.dir, 'app.json');
const own = (existsSync(manifest) ? JSON.parse(readFileSync(manifest, 'utf8')).commands : null) ?? {};
const clash = Object.keys(own).find((name) => verbs[name]);
if (clash) {
  console.error(`app.json commands.${clash}: ${clash} is one of exact.mjs's own verbs; give the app's another name`);
  process.exit(2);
}
if (!verbs[verb] && !own[verb]) {
  console.error(`Usage: bun exact.mjs <${[...Object.keys(verbs), ...Object.keys(own)].join('|')}> [arguments for that script]`);
  process.exit(2);
}
// The automatic build reports on stderr, so a drive's stdout stays its reply (`--json`).
// The child ends with this process: a signal here is passed on, and a dev server
// stops when this process is gone however it ended (`EXACT_LAUNCHER_PID`).
const spawned = (command, args, stdio = 'inherit', cwd = undefined) => new Promise((done) => {
  const child = spawn(command, args, {
    stdio,
    cwd,
    env: { ...process.env, HERMES_LEAN_SYS_OFFLINE: '1', EXACT_APP_DIR: import.meta.dir, EXACT2, EXACT_LAUNCHER_PID: String(process.pid) },
  });
  const pass = (signal) => child.kill(signal), signals = ['SIGINT', 'SIGTERM', 'SIGHUP'];
  for (const signal of signals) process.on(signal, pass);
  child.on('error', () => done(1));
  child.on('exit', (code, signal) => {
    for (const s of signals) process.off(s, pass);
    done(code ?? 128 + (constants.signals[signal] ?? 0));
  });
});
const run = ([script, ...args], more = [], stdio = 'inherit') => spawned(process.execPath, [resolve(EXACT2, script), ...args, ...more], stdio);
const started = Date.now();
// The diary's command log (exact2's docs/diary.md): which exact2, what ran, how it ended. No arguments.
const log = exit => { if (verb !== 'feedback') try {
  const exact2 = spawnSync('git', ['-C', EXACT2, 'rev-parse', '--short=9', 'HEAD'], { encoding: 'utf8' }).stdout?.trim() || null;
  mkdirSync(resolve(import.meta.dir, '.exact'), { recursive: true });
  appendFileSync(resolve(import.meta.dir, '.exact/commands.jsonl'), JSON.stringify({ at: new Date(started).toISOString(), exact2, verb: verb === 'test' || verb === 'agent' ? `${verb} ${host}` : verb, exit, ms: Date.now() - started }) + '\n');
} catch {} return exit; };
// The web build is about a second when nothing changed, so a web drive builds
// first rather than refusing a stale build; a native build stays explicit.
const drivesWeb = (verb === 'test' || verb === 'agent') && host === 'web' && !rest.some(a => a === '--url' || a === '--web-dist');
// `test [host] [file|glob …]`: the test files named (each `.contract`, a glob or `--test <file>`, from the
// current directory), else app.test.contract; each runs in turn and any failure fails the command.
const tests = [];
for (let i = verb === 'test' ? 0 : rest.length; i < rest.length;) {
  const named = rest[i] === '--test' ? rest.splice(i, 2)[1] : /\.contract$|\*/.test(rest[i]) ? rest.splice(i, 1)[0] : (i++, null);
  if (named == null) continue;
  const found = named.includes('*') ? [...new Bun.Glob(named).scanSync({ absolute: true })].sort() : [resolve(named)];
  if (!found.length) { console.error(`no test file matches ${named}`); process.exit(log(2)); }
  tests.push(...found);
}
if (drivesWeb) { const built = await run(verbs['web-build'], [], [0, 2, 2]); if (built) process.exit(log(built)); }
if (own[verb]) { const [command, ...args] = own[verb]; process.exit(log(await spawned(command === 'bun' ? process.execPath : command, [...args, ...rest], 'inherit', import.meta.dir))); }
if (verb !== 'test') process.exit(log(await run(verbs[verb], rest)));
let failed = 0;
for (const file of tests.length ? tests : [resolve(import.meta.dir, 'app.test.contract')]) {
  if (tests.length > 1) console.log(`# ${relative(process.cwd(), file)}`);
  failed = (await run(verbs.test, ['--test', file, ...rest])) || failed;
}
process.exit(log(failed));
